[ui]
title = { fg = "#00ffff", bold = true }
cursor = { bg = "#00ffff", fg = "#000000" }
selected = { bg = "#1f1f1f", fg = "#00ffff", bold = true }
border = { fg = "#3a3a3a" }

[filetype]
directory = "#5fdfff"
symlink = "#ffaf5f"
executable = "#afff87"

[status]
normal = { fg = "#c0caf5", bg = "#1a1b26" }
warning = { fg = "#ffaf00", bg = "#1a1b26", bold = true }
error = { fg = "#ff5f5f", bg = "#1a1b26", bold = true }

