[sherlock]
launcher = "all"

[style]
css = "main.css"  # Uses the custom CSS below

[layout]
width = 50
padding = 24
border_width = 2
border_radius = 14
max_results = 8
center = true

[fonts]
family = "CaskaydiaCove Nerd Font"
size = 13

